### ISSUE TITLE
One directory per stub

### ISSUE THREAD

**Issue by joneskoo** [ouspg/trytls#10]
Maybe a good idea to make the stubs one stub per directory so tests can be added?

**Comment by oherrala** [comment]
One directory per stub would allow:
- README.md for docs
- Language specific build tooling (managing library deps can be pain)
- Dockerfile so that the stub can be built & ran inside container (see build tooling above)

Example of above points in action: https://github.com/ouspg/trytls/tree/master/examples/haskell-wreq

**Comment by Mamietti** [comment]
819483c examples flattened into directory "stubs" into their own directories
